# Generated by Django 4.0.5 on 2022-06-29 07:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='color_varience',
        ),
        migrations.RemoveField(
            model_name='product',
            name='size_varience',
        ),
        migrations.DeleteModel(
            name='ColorVarient',
        ),
        migrations.DeleteModel(
            name='SizeVarient',
        ),
    ]
